name: Deploy to GoDaddy

on:
  push:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lftp
      run: sudo apt-get install lftp

    - name: Deploy to GoDaddy
      run: |
        lftp -e "
        set ftp:ssl-force true;  # Force SSL/TLS encryption
        open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftps://ftp.dumindia.in;  # Use FTPS
        mirror -R ./ /public_html/;  # Deploy files to the GoDaddy directory
        quit
        "
