on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures the full Git history is fetched to track changes

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.dumindia.in
          username: github_actions@dumindia.in
          password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: "--changed-only" # Ensures only changed files are synced
          exclude: |
            dumindia2018/**
            dumindia2019/**
            dumindia2020/**
          state-name: ".ftp-deploy-sync-state.json" # Keeps track of changes on the server
          log-level: "verbose" # Enables detailed logging for debugging purposes
